#!/bin/bash
SOMMELIER_BRANCH=$(proxychains git ls-remote https://chromium.googlesource.com/chromiumos/containers/sommelier.git | grep refs/tags/ | tail -1 | awk '{print $2}' | cut -d"/" -f3)
proxychains git clone -b $SOMMELIER_BRANCH https://chromium.googlesource.com/chromiumos/containers/sommelier.git