#! /bin/sh
set -a
GDK_BACKEND=${GDK_BACKEND:-x11}
# Adjust settings for container usage if necessary.
if [[ -f '/.dockerenv' ]]; then
	CLUTTER_BACKEND=x11
	set +a
	# Return or exit depending upon whether script was sourced.
	(return 0 2>/dev/null) && return 0 || exit 0
fi
SOMMELIER_ACCELERATORS='Super_L,<Alt>bracketleft,<Alt>bracketright'
WAYLAND_DISPLAY=wayland-0
XDG_RUNTIME_DIR=/var/run/user/1000
SOMMELIER_VM_IDENTIFIER=chromebrew
if grep -q GenuineIntel /proc/cpuinfo ;then
	check_linux_version() {
		maj_ver=$1
		min_ver=$2
		version_good=$(uname -r | awk 'BEGIN{ FS="."};
		{ if ($1 < '"${maj_ver}"') { print "N"; }
	else if ($1 == '"${maj_ver}"') {
		if ($2 < '"${min_ver}"') { print "N"; }
		else { print "Y"; }
		}
	else { print "Y"; }
	}')

	if [ "$version_good" = "N" ]; then
		return 1
	fi
}
case "$(uname -m)" in
	x86_64)
		if ! check_linux_version 4 16; then
			:
			# Mesa > 22.0 does not support i965
			# MESA_LOADER_DRIVER_OVERRIDE=i965
		elif check_linux_version 5 10; then
			MESA_LOADER_DRIVER_OVERRIDE=iris
		fi
		;;
esac
fi
CLUTTER_BACKEND=${CLUTTER_BACKEND:-wayland}
DISPLAY=${DISPLAY:-:0}
set +a
