#!/bin/bash -a
set -a
source /usr/local/etc/env.d/sommelier
set +a
mkdir -p /usr/local/var/{log,run}
checksommelierwayland () {
	[[ -f "/usr/local/var/run/sommelier-wayland.pid" ]] || return 1
		/sbin/ss --unix -a -p | grep "\b$(cat /usr/local/var/run/sommelier-wayland.pid)" | grep wayland &>/dev/null
}
checksommelierxwayland () {
	DISPLAY="${DISPLAY}" timeout 1s xset q &>/dev/null
}

## As per https://www.reddit.com/r/chromeos/comments/8r5pvh/crouton_sommelier_openjdk_and_oracle_sql/e0pfknx/
## One needs a second sommelier instance for wayland clients since at some point wl-drm was not implemented
## in ChromeOS's wayland compositor.
#if ! checksommelierwayland ; then
#  pkill -F #{CREW_PREFIX}/var/run/sommelier-wayland.pid &>/dev/null
#  rm ${XDG_RUNTIME_DIR}/wayland-1*
#  sommelier --parent \
#    --peer-cmd-prefix="#{CREW_PREFIX}#{@peer_cmd_prefix}" \
#    --drm-device=/dev/dri/renderD128 --shm-driver=noop \
#    --data-driver=noop --display=wayland-0 --socket=wayland-1 \
#    --virtwl-device=/dev/null &> #{CREW_PREFIX}/var/log/sommelier.log &
#  echo "$!" > #{CREW_PREFIX}/var/run/sommelier-wayland.pid
#fi

if ! checksommelierxwayland; then
pkill -F /usr/local/var/run/sommelier-xwayland.pid &>/dev/null
DISPLAY="${DISPLAY:0:3}"

xdg_shell_v6=''

# check if exo support xdg_wm_base
if [[ -z "$(WAYLAND_DISPLAY=wayland-0 wayland-info -i xdg_wm_base)" ]]; then
xdg_shell_v6='--xdg-shell-v6'
fi

touch ~/.Xauthority
xauth_cmd="xauth generate ${DISPLAY} . trusted"
# --enable-xshape Appears to be broken as of Feb 17, 2023.
sommelier_cmd="sommelier -X \
	       --x-display=${DISPLAY} \
	       --scale=${SCALE} \
	       ${SOMMELIER_DIRECT_SCALE} \
	       --glamor \
	       --force-drm-device=${SOMMELIER_DRM_DEVICE} \
	       --display=wayland-0 \
	       --xwayland-path=/usr/bin/Xwayland \
	       --xwayland-gl-driver-path=/usr/lib/dri64 \
	       --peer-cmd-prefix=/lib64/ld-linux-x86-64.so.2 \
	       --noop-driver ${xdg_shell_v6} \
	       --no-exit-with-child \
	       /bin/sh -c ${xauth_cmd}"
	       echo "$sommelier_cmd" >> /usr/local/var/log/sommelier.log
	       $sommelier_cmd &>> /usr/local/var/log/sommelier.log &

	       pgrep Xwayland > /usr/local/var/run/sommelier-xwayland.pid
	       xhost +si:localuser:root
	       fi
