#!/bin/bash
mkdir -p /usr/local/var/log && touch /usr/local/var/log/sommelier.log
# Quickest way is to use killall on Xwayland
pgrep Xwayland &>> /usr/local/var/log/sommelier.log && killall Xwayland
SOMM="$(pgrep -fc sommelier.elf 2> /dev/null)"
if [[ "${SOMM}" -gt "0" ]]; then
	pkill -f sommelier.elf &>> /usr/local/var/log/sommelier.log
	pkill -F /usr/local/var/run/sommelier-wayland.pid &>> /usr/local/var/log/sommelier.log
	pkill -F /usr/local/var/run/sommelier-xwayland.pid &>> /usr/local/var/log/sommelier.log
else
	# Return or exit depending upon whether script was sourced.
	(return 0 2>/dev/null) && return 0 || exit 0
fi
if [[ "$(pgrep -fc sommelier.elf 2> /dev/null)" -gt "0" ]]; then
	echo "sommelier failed to stop"
	# Return or exit depending upon whether script was sourced.
	(return 0 2>/dev/null) && return 1 || exit 1
else
	echo "sommelier stopped"
fi
